apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    purpose: service-demo
spec:
  selector:
    purpose: service-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: dev
  ports:
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    purpose: service-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: dev
spec:
  containers:
  - name: nginx
    image: nginx