apiVersion: v1
kind: Service
metadata:
  name: nginx-np-service
  labels:
    purpose:  service-np-demo
spec:
  type: NodePort
  selector:
    purpose: service-np-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: nginx
  ports:
    - protocol: TCP
      port: 80  # service port
      targetport: 80  # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np-service
  labels:
    purpose: service-np-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: nginx
spec:
  containers:
    - name: nginx
      image: nginx