apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb-service 
  labels: 
    purpose: service-lb-demo
spec:
  type: LoadBalancer
  selector:
    purpose: service-lb-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: nginx
  ports:
    - protocol: TCP
      port: 80  # service port
      targetPort: 80  # container port
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    purpose: service-lb-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: nginx
spec:
  containers:
    - name: nginx
      image: nginx