apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  # replica set labels
  labels:
    purpose: rs-demo
    project: roboshop
    environment: dev
    tier: frontend
    component: nginx
spec:
  replicas: 2
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchlabels:
      purpose: rs-demo
      project: roboshop
      environment: dev
      tier: frontend
      component: nginx
    # This is pod definition
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
        environment: dev
        tier: frontend
        component: nginx
    spec:
      containers:
      - name: nginx
        image nginx 